version: 1.2
workflows:
   - name: wdl_pathogen_build
     subclass: WDL
     primaryDescriptorPath: /workflow.wdl
     testParameterFiles:
     - /input_ncov.json
     authors:
      - name: Nextstrain